[wokwi]
version = 1
#gdbServerPort = 3333
elf = "uf2.bin"
firmware = "uf2.bin"

[[chip]]
name = 'inverter'  # To use the chip in diagram.json, add a part with "chip-inverter" type.
binary = 'target/wasm32-unknown-unknown/release/chip_inverter.wasm'
